services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-erp_user}
      POSTGRES_PASSWORD: ${DB_PASS:-erp_pass}
      POSTGRES_DB: ${DB_NAME:-erp_db}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    command: sh -c "./wait-for-db.sh && npm run dev"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    ports:
      - "4001:4000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules

volumes:
  db-data:
