/**
 * Super Admin Security Incident Notifier
 * Sends out-of-band alerts for critical security incidents to platform Super Admins.
 * Never exposes security alerts or incident data to regular users or tenant accounts.
 */

const logger = require('./logger');

let resendClient = null;
if (process.env.RESEND_API_KEY) {
  try {
    const { Resend } = require('resend');
    resendClient = new Resend(process.env.RESEND_API_KEY);
  } catch (err) {
    logger.warn(`[SecurityNotifier] Resend module init warning: ${err.message}`);
  }
}

/**
 * Dispatches an alert to the Super Admin upon critical incident creation.
 * Non-blocking: errors are caught and logged without affecting request flow or worker processing.
 *
 * @param {Object} params
 * @param {Object} params.incident - Security incident record
 */
async function notifySuperAdminCriticalIncident({ incident }) {
  if (!incident || incident.severity !== 'critical') return;

  const targetEmail = process.env.SUPER_ADMIN_EMAIL || 'prozyncinnovations@gmail.com';
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'security-alerts@prozync.in';

  const subject = `🚨 CRITICAL SECURITY ALERT: ${incident.threat_category} on SmartERP`;
  const htmlContent = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; background: #0f172a; color: #f8fafc; border-radius: 12px;">
      <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">
        <span style="background: #ef4444; color: white; padding: 4px 10px; border-radius: 6px; font-weight: bold; font-size: 12px; letter-spacing: 1px;">CRITICAL INCIDENT</span>
        <span style="color: #94a3b8; font-size: 12px; font-family: monospace;">INCIDENT #${(incident.id || '').substring(0, 8)}</span>
      </div>
      
      <h2 style="color: #ffffff; margin: 0 0 12px 0; font-size: 20px;">${incident.title || 'Security Anomaly Detected'}</h2>
      
      <div style="background: #1e293b; border-radius: 8px; padding: 16px; margin-bottom: 20px; border: 1px solid #334155;">
        <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
          <tr>
            <td style="color: #94a3b8; padding: 6px 0;">Threat Category:</td>
            <td style="color: #f1f5f9; font-weight: bold; font-family: monospace;">${incident.threat_category}</td>
          </tr>
          <tr>
            <td style="color: #94a3b8; padding: 6px 0;">Calculated Risk Score:</td>
            <td style="color: #ef4444; font-weight: bold; font-family: monospace;">${incident.risk_score} / 100</td>
          </tr>
          <tr>
            <td style="color: #94a3b8; padding: 6px 0;">Source IP:</td>
            <td style="color: #f1f5f9; font-family: monospace;">${incident.source_ip || 'Internal / Multiple'}</td>
          </tr>
          <tr>
            <td style="color: #94a3b8; padding: 6px 0;">Correlated Signals:</td>
            <td style="color: #f1f5f9;">${incident.event_count || 1} events</td>
          </tr>
        </table>
      </div>

      <p style="color: #94a3b8; font-size: 12px; line-height: 1.5; margin-bottom: 24px;">
        This alert was generated by the deterministic sliding-window correlation engine. Access the Super Admin Security Operations Center to review AI threat enrichment and execute or approve remediation actions.
      </p>

      <a href="${process.env.FRONTEND_ORIGIN || 'https://www.prozync.in'}/superadmin/security" 
         style="display: inline-block; background: #dc2626; color: #ffffff; text-decoration: none; padding: 10px 20px; border-radius: 8px; font-size: 13px; font-weight: bold;">
        Open Security Operations Center →
      </a>
      
      <hr style="border: 0; border-top: 1px solid #334155; margin: 24px 0;" />
      <p style="color: #64748b; font-size: 11px; margin: 0;">
        SmartERP Autonomous Defense System • Strictly confidential platform alert.
      </p>
    </div>
  `;

  if (resendClient) {
    try {
      await resendClient.emails.send({
        from: fromEmail,
        to: targetEmail,
        subject,
        html: htmlContent
      });
      logger.info(`[SecurityNotifier] Dispatched critical incident email to Super Admin: ${targetEmail}`);
    } catch (err) {
      logger.warn(`[SecurityNotifier] Resend email alert failed (non-fatal): ${err.message}`);
    }
  } else {
    logger.info(`[SecurityNotifier] [LOCAL/FALLBACK] Critical Incident Alert for Super Admin (${targetEmail}): ${subject}`);
  }
}

module.exports = {
  notifySuperAdminCriticalIncident
};
